### ISSUE TITLE
Game Plan

### ISSUE THREAD

**Issue by MggMuggins** [HubTou/LotrSupportInOverviewer#1]
What are we thinking to do to update this monstrosity? Hand coding will probably be easiest, but that will take forever. Hub, do you know how possible it would be to write a script or a program of some kind to update it automatically?
~Samwise

**Comment by HubTou** [comment]
It's not possible to do it fully automatically, but it could be made a little bit easier.

At least, you would have to manually provide some file associating:
- a block name (the ID is local to the server instance, thus the Makefile doing the association)
- one or more LOTR Mod textures (whose filename(s) might not be directly related to the block name
- a type of block to be rendered (unfortunately, apart from plain cubic blocks, there are plenty that need tailor made code to render them, including some I was not able to figure how to do) 

Then you could have a script spitting out the [lotr_textures.py.template](https://github.com/HubTou/LotrSupportInOverviewer/blob/master/lotr_textures.py.template) file.

All this could be done by a new shell script called from the Makefile.

Then it might be interesting to add a script to analyse what needs to be done, by identifying new blocks & textures, not already supported in the current supported version.

But with all blocks being renamed in beta 30.x of the mod, this would require some work before.

**Comment by MggMuggins** [comment]
I'm going to need to look through the code a bit more carefully and see what all needs to happen. I'll make something up as I go along.
~Samwise

**Comment by HubTou** [comment]
As this is not a real issue with the existing release, I'm closing this discussion thread now.
Let's continue the discussion about this update project on the tool's [own page](http://lotr-minecraft-mod-exiles.wikia.com/wiki/LOTR_mod_support_in_the_Minecraft_Overviewer).

**Comment by MggMuggins** [comment]
I've seen many projects that use an issue as a way to easily communicate in a way that is solidly related to the topic. Also I don't really like page comments for serious discussion, because I don't receive any notification for them. I'll make a thread on the Forums...
