### ISSUE TITLE
B31 Makefile

### ISSUE THREAD

**Issue by MggMuggins** [HubTou/LotrSupportInOverviewer#5]
With my pull request ( #4)  I changed the mod version in the makefile. I forsee this being a problem for downloading the mod. Hub, could you update your server to make sure that the mod can be brought down without 404 error?

**Comment by HubTou** [comment]
Done. [Beta31](http://harda.tournier.org/files/The_Lord_of_the_Rings_Mod_B31.jar) and [Beta30.5](http://harda.tournier.org/files/The_Lord_of_the_Rings_Mod_B30.5.jar) are now available for direct download.

**Comment by MggMuggins** [comment]
Cool, thanks Hub. I'm also working back and forth between updating the textures.py.template (working with it as textures.py so that kwrite will do syntax highlighting...) and building the test world. NEI is so useful...

**Comment by HubTou** [comment]
Beta 31.1 is also downloadable using the same naming scheme.

**Comment by MggMuggins** [comment]
Cool. I'll probably leave it in the makefile unless there is some texture change. No need to add more clutter.
